### ISSUE TITLE
some requests

### ISSUE THREAD

**Issue by conradaaron21** [AlexeyGurevsky/bbtube#3]
Your app great. Thank you so much Alex! Thanks to you, you can go on using my bb. 
Could you please add these features to the app?
-video/audio speed setting (x1,25 x1,5...)
- quality settings (144p mp4... , 48 kbps m4a)

**Comment by AlexeyGurevsky** [comment]
Hi @conradaaron21 
The thing is that BB shut down its services few months ago, so it's not possible to develop or release anything new.
Besides that, I tried to implement the features you're requesting but it turned out that BB 10 platform didn't have necessary codecs.

**Comment by conradaaron21** [comment]
> Hi @conradaaron21 The thing is that BB shut down its services few months ago, so it's not possible to develop or release anything new. Besides that, I tried to implement the features you're requesting but it turned out that BB 10 platform didn't have necessary codecs.

Thanks for your answer! I wonder one other thing when I read your comment.
If one day bbtube is over because of youtube's api, Are you able to create an apk youtube app that support Android 4.3 and lower? Do you have any knowledge about creating android apk?

**Comment by AlexeyGurevsky** [comment]
@conradaaron21 I'd rather use NewPipe legacy edition instead.
Talk to the author of https://forums.crackberry.com/blackberry-10-os-f269/adapted-android-applications-tips-tricks-1173929/ for more details
